config/routes.rb
Rails.application.routes.draw do
	resources :champion, only: [:index]
  root 'champion#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/champion.rb
class Champion < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/champion_controller.rb
class ChampionController < ApplicationController
  def index
  	@champion = Champion.order(params[:sort])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/champion_helper.rb
module ChampionHelper
end

app/views/champion/index.html.erb
<div id="topHeader">
	<%= image_tag("", :id => "champIconHeader") %>
</div>
<table>
		<th>Icon</th>
		<% @champion.column_names.each_with_index do |column, index| %>
			<% next if index <= 2 || index > 28 %>
			<th>
				<%= column %>
				<%= link_to image_tag("icon-arrow-up-b-128.png",
															:class => "sort-button",
															size: "10",
															alt: "Sort"), 
															champion_index_path(sort: "#{column}") %>
				<%= link_to image_tag("icon-arrow-down-b-128.png",
															:class => "sort-button",
															size: "10",
															alt: "Sort"), 
															champion_index_path(sort: "#{column} DESC") %>
			</th>
		<% end %>

	<% @champion.each do |champion| %>
		<tr>
			<td><%= image_tag("#{champion.image_url}", :class => "champIcon") %></td>
			<td class="colchampname"><%= champion.name %></td>
			<td><%= champion.armor %></td>
			<td><%= champion.armorperlvl %></td>
			<td><%= champion.ad %></td>
			<td><%= champion.adperlvl %></td>
			<td><%= champion.autorange.to_i %></td>
			<td><%= champion.asoffset %></td>
			<td><%= champion.asperlvl %></td>
			<td><%= champion.hp %></td>
			<td class="colhplvl"><%= champion.hpperlvl %></td>
			<td><%= champion.hpregen %></td>
			<td><%= champion.hpregenperlvl %></td>
			<td><%= champion.ms.to_i %></td>
			<td><%= champion.mp %></td>
			<td><%= champion.mpperlvl %></td>
			<td><%= champion.mpregen %></td>
			<td><%= champion.mpregenperlvl %></td>
			<td><%= champion.mr %></td>
			<td><%= champion.mrperlvl %></td>
			<td><%= champion.adatmax %></td>
			<td><%= champion.armoratmax %></td>
			<td><%= champion.hpatmax %></td>
			<td><%= champion.hpregenatmax %></td>
			<td><%= champion.mpatmax %></td>
			<td><%= champion.mpregenatmax %></td>
			<td><%= champion.asatmax %></td>
		<tr>
	<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lolstats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header></header>
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>